# Jekyll configuration
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 10
language: 'en-uk'

# Website info
title: 'Potentiometrics'
description: "Machine Learning for Human Learners"

# google_analytics: UA-69281367-1
disqus: username
baseurl: /

# Permalinks
permalink: /posts/:title

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts

exclude:
  - .git
  - setup
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
